#!/bin/sh
#
# Copyright (c) 2025 Andrew Krasichkov
# Copyright (c) 2017 Shawn Rose
#
# Author: Andrew Krasichkov <dev@buglloc.cc>
# Author: Shawn Rose <shawnandrewrose@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

PREREQ=""

prereqs() {
  echo "$PREREQ"
}

case "$1" in
  prereqs)
    prereqs
    exit 0
  ;;
esac

[ -s /run/boundbox.pid ] || exit 0

if [ -e /etc/boundbox/boundbox.conf ]; then
  . /etc/boundbox/boundbox.conf
fi
. /scripts/functions


pid=$(cat /run/boundbox.pid)
child_pids="$({ ps -o pid,ppid 2>/dev/null || ps -l ||
  { echo 'boundbox: unable to get list of processes' >&2; exit 1; }; } |
  awk -v pid="$pid" '
    NR==1 {
      for (i=1; i<=NF; i++) if ($i == "PID") pid_col = i; else if ($i == "PPID") ppid_col = i
      if (!pid_col || !ppid_col) { print "boundbox: unable to find PID and/or PPID columns in ps output" | "cat >&2"; exit 1 }
      next
    }
    { if ($ppid_col == pid) print $pid_col }')"

log_begin_msg "Stopping BoundBox"

for kill_pid in $pid $child_pids; do
  kill -TERM "$kill_pid" 2>/dev/null
done

rm -f /run/boundbox.pid
log_end_msg

# Not really worried about downing extra interfaces: they will come up
# during the actual boot. Might make this configurable later if needed.

if [ "$BOOT" != nfs ] && [ "$IFDOWN" != none ]; then
  for IFACE in /sys/class/net/$IFDOWN; do
    [ -e "$IFACE" ] || continue
    IFACE="${IFACE#/sys/class/net/}"
    log_begin_msg "Bringing down $IFACE"
    ip link    set   dev "$IFACE" down
    ip address flush dev "$IFACE"
    ip route   flush dev "$IFACE"
    log_end_msg
  done
fi
